fail_fast: false # do not stop after failure (can still interupt manually...)
repos:
  # Add some general purpose useful hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # Make sure that contained YAML files are well-formed
      - id: check-yaml
      # Trim trailing whitespace of all sorts
      - id: trailing-whitespace
      # Simple parser validation of e.g. pyproject.toml
      - id: check-toml
      # Unify file endings
      - id: end-of-file-fixer
      # Normalize to LF line endings (Unix-style)
      - id: mixed-line-ending
        args: [--fix=lf]
      # Prevent committing private keys
      - id: detect-private-key
      # Ensure no merge conflict markers are committed
      - id: check-merge-conflict
      # Detect case conflicts in filenames, on macOS/Windows filenames are case-insensitive, but not on Linux
      - id: check-case-conflict
      # Check for python syntax errors
      - id: check-ast

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.9
    hooks:
      - id: ruff
        types_or: [python] # ignore jupyter for now [python, jupyter]
        args: [--fix]
      - id: ruff-format
        types_or: [python] # ignore jupyter for now [python, jupyter]

  # pytest hook to run tests on commit
  - repo: local
    hooks:
      - id: pytest
        name: Run pytest
        #entry: pytest --cov partipy --cov-report=html
        entry: pytest
        language: system
        types: [python]
        pass_filenames: false
        always_run: true

  # type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
